# Generated by Django 4.2.1 on 2023-06-02 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_attendance_question"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "출결", "verbose_name_plural": "출결 목록"},
        ),
    ]
