# Generated by Django 4.2.1 on 2023-06-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_delete_profile_alter_attendance_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "출석"), (2, "결석 (사유 필히 작성)"), (3, "일부 일정 불참 (사유 필히 작성)")],
                verbose_name="출석여부",
            ),
        ),
    ]
