# Generated by Django 4.2.1 on 2023-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "출석"), (2, "결석"), (3, "일부 일정 불참")], verbose_name="출석여부"
            ),
        ),
    ]
