# Generated by Django 4.2.1 on 2023-06-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_alter_question_screenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="screenshot",
            field=models.ImageField(
                default="default_img/명탐정피카20.gif", upload_to="", verbose_name="스크린샷"
            ),
        ),
    ]
